# Generated by Django 4.2.3 on 2023-07-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_access',
            field=models.DateTimeField(null=True),
        ),
    ]
