# Generated by Django 4.2.3 on 2023-07-31 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_task_last_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmember',
            old_name='user_id',
            new_name='user',
        ),
    ]
